Parameters:
  NamePrefix:
    Type: String
Resources:
  StateBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${NamePrefix}-tofu-state-${AWS::Region}-${AWS::AccountId}"
      VersioningConfiguration:
        Status: "Enabled"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      OwnershipControls:
        Rules:
          - ObjectOwnership: "BucketOwnerEnforced"
  LockTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${NamePrefix}-tofu-lock"
      BillingMode: "PAY_PER_REQUEST"
      AttributeDefinitions:
        - AttributeName: "LockID"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "LockID"
          KeyType: "HASH"
  StateBucketName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "${NamePrefix}-state-bucket"
      Type: String
      Value: !Ref StateBucket
  LockTableName:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "${NamePrefix}-lock-table"
      Type: String
      Value: !Ref LockTable