package org.ttt.commons;

import static software.amazon.awssdk.enhanced.dynamodb.internal.AttributeValues.numberValue;

import java.time.ZoneOffset;
import java.time.ZonedDateTime;
import java.util.Optional;
import java.util.UUID;
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedClient;
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbTable;
import software.amazon.awssdk.enhanced.dynamodb.Expression;
import software.amazon.awssdk.enhanced.dynamodb.TableSchema;
import software.amazon.awssdk.enhanced.dynamodb.extensions.AtomicCounterExtension;
import software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedTimestampRecordExtension;
import software.amazon.awssdk.enhanced.dynamodb.model.TransactUpdateItemEnhancedRequest;
import software.amazon.awssdk.enhanced.dynamodb.model.TransactWriteItemsEnhancedRequest;
import software.amazon.awssdk.services.dynamodb.DynamoDbClient;

public class GamesService {
  private final DynamoDbTable<Game> gamesTable;
  private final DynamoDbTable<GameCount> gamesCountTable;
  private final DynamoDbEnhancedClient enhancedClient;
  private final int maxGamesCount;

  public GamesService() {
    DynamoDbEnhancedClient client =
        DynamoDbEnhancedClient.builder()
            .dynamoDbClient(DynamoDbClient.create())
            .extensions(
                AutoGeneratedTimestampRecordExtension.create(),
                AtomicCounterExtension.builder().build())
            .build();
    this.enhancedClient = client;
    String gamesTableName = System.getenv("GAMES_TABLE_NAME");
    this.gamesTable = client.table(gamesTableName, TableSchema.fromClass(Game.class));
    String gamesCountTableName = System.getenv("GAMES_COUNT_TABLE_NAME");
    maxGamesCount = Integer.parseInt(System.getenv("MAX_GAMES_COUNT"));
    this.gamesCountTable =
        client.table(gamesCountTableName, TableSchema.fromClass(GameCount.class));
  }

  public Optional<Game> getGame(String gameId) {
    return Optional.ofNullable(gamesTable.getItem(Game.builder().gameId(gameId).build()));
  }

  public Game createNewGame(CreateGameRequest request) {
    UUID uuid = UUID.randomUUID();
    ZonedDateTime now = ZonedDateTime.now(ZoneOffset.UTC);
    Game game =
        Game.builder()
            .gameId(uuid.toString())
            .playerId(request.hostPlayerId())
            .opponent(request.opponentId())
            .created(now)
            .lastUpdate(now)
            .build();
    GameCount gameCount = GameCount.builder().playerId(request.hostPlayerId()).build();
    enhancedClient.transactWriteItems(
        TransactWriteItemsEnhancedRequest.builder()
            .addPutItem(gamesTable, game)
            .addUpdateItem(
                gamesCountTable,
                TransactUpdateItemEnhancedRequest.builder(GameCount.class)
                    .item(gameCount)
                    .conditionExpression(
                        Expression.builder()
                            // This checks existing value before atomic increment, then performs the
                            // update
                            .expression("attribute_not_exists(activeGames) OR activeGames < :limit")
                            .putExpressionValue(":limit", numberValue(maxGamesCount))
                            .build())
                    .build())
            .build());
    return game;
  }
}
