package org.ttt.commons;

import java.time.Instant;
import lombok.Builder;
import lombok.Getter;
import lombok.Value;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAtomicCounter;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.UpdateBehavior;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbImmutable;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbUpdateBehavior;

@Value
@Builder
@DynamoDbImmutable(builder = GameCount.GameCountBuilder.class)
public class GameCount {
  @Getter(onMethod_ = @DynamoDbPartitionKey)
  String playerId;

  @Getter(onMethod_ = @DynamoDbAtomicCounter(startValue = 1))
  Integer activeGames;

  @Getter(onMethod_ = @DynamoDbAutoGeneratedTimestampAttribute)
  Instant lastUpdate;

  @Getter(
      onMethod_ = {
        @DynamoDbAutoGeneratedTimestampAttribute,
        @DynamoDbUpdateBehavior(UpdateBehavior.WRITE_IF_NOT_EXISTS)
      })
  Instant created;
}
