openapi: "3.0.1"
info:
  version: "1.0.0"
  title: "Tic Tac Toe"
paths:
  /games/{gameId}/moves:
    parameters:
      - name: gameId
        description: "Game Identifier"
        in: path
        required: true
        schema:
          type: string
    post:
      operationId: playerMove
      description: "Adds new player move"
      x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri: "${player_move_arn}"
        payloadFormatVersion: "2.0"
        passthroughBehavior: when_no_templates
      requestBody:
          content:
            'application/json':
              schema:
                $ref: '#/components/schemas/PlayerMove'
      responses:
        200:
          description: "Move properly commited"
components:
  schemas:
    PlayerMove:
      type: object
      properties:
        positionX:
          type: number
        positionY:
          type: number
        symbol:
          type: string
          enum:
            - CROSS
            - NOUGHT
